<?php
/**
 * @file
 * Current F1 Driver Standings
*/
/**
 * Implements hook_block_info
 */
function driver_standings_block_info() {
    $blocks = array();
    $blocks['driver_standings'] = array(
        'info'  =>  t('Current Driver Standings')
    );
    return $blocks;
 } 

/**
  * Implements hook_block_view
*/
function driver_standings_block_view($delta='') {
    $blocks = array();
    switch ($delta) {
        case 'driver_standings':
        //$blocks['titles'] = t('Driver Standings.');
        $blocks['content'] = t('<h3>Driver Standings</h3><p>Working on it...</p>');
        
        break;
    }
    return $blocks;
}