<?php
/**
 * @file
 * Current F1 Driver Standings
*/
/**
 * Implements hook_block_info
 */
function driver_standings_block_info() {
    $blocks = array();
    $blocks['driver_standings'] = array(
        'info'  =>  t('Current Driver Standings')
    );
    return $blocks;
 } 

/**
  * Implements hook_block_view
*/
function driver_standings_block_view($delta='') {
    $blocks = array();
    switch ($delta) {
        case 'driver_standings':
        //$blocks['titles'] = t('Driver Standings.');
        $api = simplexml_load_file('http://ergast.com/api/f1/current/driverStandings');
       $output = '<table><thead>
       <tr>
        <th>POS</th>
        <th>Driver</th>
        <th>Nationality</th>
        <th>Team</th>
        <th>Points</th>
       </tr>
       </thead><tbody>';
        foreach($api->StandingsTable->StandingsList as $driver) {
            for ($i=0; $i < 20; $i++) { 
                $output .= '<tr><td>' . ($i+1) . '</td>';
                $output .= '<td>' . $driver->DriverStanding[$i]->Driver->FamilyName . '</td>';
                $output .= '<td>' . $driver->DriverStanding[$i]->Driver->Nationality . '</td>';
                $output .= '<td>' . $driver->DriverStanding[$i]->Constructor->Name . '</td>';
                $output .= '<td>' . $driver->DriverStanding[$i]['points'] . '</td></tr>';
            }
        }
        $output .= '</tbody></table>';
        $blocks['content'] = $output;
        
        break;
    }
    return $blocks;
}