<?php
/**
 * @file
 *  Last Git commit
 */

/**
 * Implements hook_block_info
 */
function last_git_commit_block_info() {
    $blocks = array();
    $blocks['last_git_commit'] = array(
        'info' => t('Shows last git commit')
    );
    return $blocks;
}

/**
 * Implements hook_block_view
 * This will show our last git commit, and will allow us to see it on the github project's page
*/

function last_git_commit_block_view($delta, $branch = "master") {
    $blocks = array();

    switch ($delta) {
        case 'last_git_commit':
        
        //$branch = '';
        $master = "sites/all/.git/refs/heads/$branch";

        $file =  $master;
        // We try to find the file, if it's not found we do nothing.
       if(file_exists($file)) {
            $content = file_get_contents($file);
            $arr = explode(' ', $content);
            
            $last_commit = substr(file_get_contents($file), 0, 7);
            
            $blocks['content'] = t('<a href="https://github.com/nouaryk/Drupal7-f1-modules-themes/commit/' . $content . ' "> ' . $last_commit . ' </a>');
        }
            break;
        
    }
    return $blocks;
}