<?php

/**
 * @file
 * A module that creates a custom block
 */


/**
  * Implements hook_block_info()
*/
function next_race_block_info() {

    $blocks['next_race'] = array(
      'info' => t('Next F1 Race Module')
    );
    return $blocks;
}

/**
 * Implements hook_block_view()
*/
function next_race_block_view($delta = '') {
    $block = array();
    switch ($delta) {
      case 'next_race':
        //$block['subject'] = t('Next F1 race');
        ob_start();
        include "next_race_content.php";
        $block['content'] = ob_get_contents();
        ob_end_clean();
        break;
    }
    return $block;
  }